title: Too Late Now
author: Jeffas
email: dev@jeffas.io
description: >-
  Correctness, Efficiency, Performance
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jeffas.io"

gitlab_username: jeffas
rss: RSS

permalink: pretty

github_username: jeffa5
rss: RSS

minima:
  date_format: "%-d %b, %Y"

# Build settings
markdown: kramdown

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
